[env]
FZG_EDITOR = "vim"

[tools]
kubectl = "latest"
helm = "latest"
k9s = "latest"
kubectx = "latest"
kubens = "latest"

[bootstrap.packages]
"apt:vim" = "latest"
"apt:bash-completion" = "latest"

[bootstrap.files."~/.miserc.local.toml"]
content = '''
env = ["server"]
'''
