[tools]
fzf = "latest"
starship = "latest"
zoxide = "latest"
rg = "latest"
fd = "latest"
bat = "latest"
delta = "latest"
eza = "latest"
lazygit = "latest"
jq = "latest"
yq = "latest"

# Kubernetes
kubectl = "latest"
helm = "latest"
k9s = "latest"
kubectx = "latest"
kubens = "latest"
zellij = "latest"
broot = { version = "latest", bin_path = '{{ arch(x64="x86_64", arm64="aarch64") }}-{{ os(macos="apple-darwin", linux="unknown-linux-gnu", windows="pc-windows-gnu") }}' }
gh = "latest"
dust = "latest"
duf = "latest"
xh = "latest"

[settings]
auto_update = true

[dotfiles]
"~/.aliases" = { mode = "track" }
"~/.bashrc" = { mode = "track", variants = [{ os = "linux" }] }
"~/.common.sh" = { mode = "track" }
"~/.config/bat/config" = { mode = "track" }
"~/.config/iterm2/com.googlecode.iterm2.plist" = { mode = "track", variants = [{ os = "macos" }] }
"~/.config/mise/config.personal.toml" = { mode = "track" }
"~/.config/mise/config.server.toml" = { mode = "track" }
"~/.config/mise/config.toml" = { mode = "track" }
"~/.config/mise/config.work.toml" = { mode = "track" }
"~/.config/shell/completion.bash" = { mode = "track" }
"~/.config/starship.toml" = { mode = "track" }
"~/.config/zellij/config.kdl" = { mode = "track" }
"~/.gitconfig" = { mode = "track" }
"~/.zshrc" = { mode = "track", variants = [{ os = "macos" }] }
