[env]
FZG_EDITOR = "code"

[settings.github]
credential_command = 'gh auth token --hostname "$MISE_CREDENTIAL_HOST"'

[tools]
bun = "latest"
pnpm = "latest"
node = "24"

[bootstrap.packages]
"brew-cask:iterm2" = "latest"
"brew-cask:font-jetbrains-mono-nerd-font" = "latest"

[bootstrap.files."~/.miserc.local.toml"]
content = '''
env = ["personal"]
'''
